/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.2.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.skyhigh.daycareapi.controller;

import java.util.List;
import java.time.OffsetDateTime;

import com.skyhigh.daycareapi.model.dto.ParentDto;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-03-25T11:14:24.149504-03:00[America/Halifax]")
@Validated
@Tag(name = "parent", description = "Operations about parent")
public interface ParentApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /parent : Create parent
     * This can be done by parent themself.
     *
     * @param parentDto Parent object (required)
     * @return Successful operation (status code 201)
     *         or Operation failed (status code 400)
     */
    @Operation(
            operationId = "createParent",
            summary = "Create parent",
            tags = { "Parent" },
            responses = {
                    @ApiResponse(responseCode = "201", description = "Successful operation", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = ParentDto.class))
                    }),
                    @ApiResponse(responseCode = "400", description = "Operation failed")
            }
    )
    @RequestMapping(
            method = RequestMethod.POST,
            value = "/parent",
            produces = { "application/json" },
            consumes = { "application/json" }
    )
    default ResponseEntity<ParentDto> createParent(
            @Parameter(name = "ParentDto", description = "Parent object", required = true) @Valid @RequestBody ParentDto parentDto
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"firstName\" : \"firstName\", \"lastName\" : \"lastName\", \"password\" : \"password\", \"address\" : { \"country\" : \"country\", \"address\" : \"address\", \"city\" : \"city\", \"postalCode\" : \"postalCode\", \"state\" : \"state\", \"locationCoordinates\" : \"locationCoordinates\", \"apartment\" : \"apartment\" }, \"phone\" : \"phone\", \"children\" : [ { \"firstName\" : \"firstName\", \"lastName\" : \"lastName\", \"dob\" : \"dob\", \"sex\" : \"sex\", \"id\" : 1 }, { \"firstName\" : \"firstName\", \"lastName\" : \"lastName\", \"dob\" : \"dob\", \"sex\" : \"sex\", \"id\" : 1 } ], \"parentStatus\" : 6, \"id\" : 0, \"email\" : \"email\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /parent/{id} : Delete Parent by id
     * This can be done only by admin after receiving a written request from the parent
     *
     * @param id Numeric ID of the parent to delete (required)
     * @return Successful operation (status code 200)
     *         or Operation failed (status code 400)
     */
    @Operation(
            operationId = "deleteParent",
            summary = "Delete Parent by id",
            tags = { "Parent" },
            responses = {
                    @ApiResponse(responseCode = "200", description = "Successful operation", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = ParentDto.class))
                    }),
                    @ApiResponse(responseCode = "400", description = "Operation failed")
            }
    )
    @RequestMapping(
            method = RequestMethod.DELETE,
            value = "/parent/{id}",
            produces = { "application/json" }
    )
    default ResponseEntity<ParentDto> deleteParent(
            @Parameter(name = "id", description = "Numeric ID of the parent to delete", required = true) @PathVariable("id") Integer id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"firstName\" : \"firstName\", \"lastName\" : \"lastName\", \"password\" : \"password\", \"address\" : { \"country\" : \"country\", \"address\" : \"address\", \"city\" : \"city\", \"postalCode\" : \"postalCode\", \"state\" : \"state\", \"locationCoordinates\" : \"locationCoordinates\", \"apartment\" : \"apartment\" }, \"phone\" : \"phone\", \"children\" : [ { \"firstName\" : \"firstName\", \"lastName\" : \"lastName\", \"dob\" : \"dob\", \"sex\" : \"sex\", \"id\" : 1 }, { \"firstName\" : \"firstName\", \"lastName\" : \"lastName\", \"dob\" : \"dob\", \"sex\" : \"sex\", \"id\" : 1 } ], \"parentStatus\" : 6, \"id\" : 0, \"email\" : \"email\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /parent : Edit parent
     * This can be done by admin or Parent
     *
     * @param parentDto Created parent object (required)
     * @return Successful operation (status code 200)
     *         or Operation failed (status code 400)
     */
    @Operation(
            operationId = "editParent",
            summary = "Edit parent",
            tags = { "Parent" },
            responses = {
                    @ApiResponse(responseCode = "200", description = "Successful operation", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = ParentDto.class))
                    }),
                    @ApiResponse(responseCode = "400", description = "Operation failed")
            }
    )
    @RequestMapping(
            method = RequestMethod.PUT,
            value = "/parent",
            produces = { "application/json" },
            consumes = { "application/json" }
    )
    default ResponseEntity<ParentDto> editParent(
            @Parameter(name = "ParentDto", description = "Created parent object", required = true) @Valid @RequestBody ParentDto parentDto
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"firstName\" : \"firstName\", \"lastName\" : \"lastName\", \"password\" : \"password\", \"address\" : { \"country\" : \"country\", \"address\" : \"address\", \"city\" : \"city\", \"postalCode\" : \"postalCode\", \"state\" : \"state\", \"locationCoordinates\" : \"locationCoordinates\", \"apartment\" : \"apartment\" }, \"phone\" : \"phone\", \"children\" : [ { \"firstName\" : \"firstName\", \"lastName\" : \"lastName\", \"dob\" : \"dob\", \"sex\" : \"sex\", \"id\" : 1 }, { \"firstName\" : \"firstName\", \"lastName\" : \"lastName\", \"dob\" : \"dob\", \"sex\" : \"sex\", \"id\" : 1 } ], \"parentStatus\" : 6, \"id\" : 0, \"email\" : \"email\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /parent/{id} : Get parent by id
     * This can be done by respective user or admin
     *
     * @param id Numeric ID of the parent to get (required)
     * @return Successful operation (status code 200)
     *         or Operation failed (status code 400)
     */
    @Operation(
            operationId = "getParent",
            summary = "Get parent by id",
            tags = { "Parent" },
            responses = {
                    @ApiResponse(responseCode = "200", description = "Successful operation", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = ParentDto.class))
                    }),
                    @ApiResponse(responseCode = "400", description = "Operation failed")
            }
    )
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/parent/{id}",
            produces = { "application/json" }
    )
    default ResponseEntity<ParentDto> getParent(
            @Parameter(name = "id", description = "Numeric ID of the parent to get", required = true) @PathVariable("id") Integer id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"firstName\" : \"firstName\", \"lastName\" : \"lastName\", \"password\" : \"password\", \"address\" : { \"country\" : \"country\", \"address\" : \"address\", \"city\" : \"city\", \"postalCode\" : \"postalCode\", \"state\" : \"state\", \"locationCoordinates\" : \"locationCoordinates\", \"apartment\" : \"apartment\" }, \"phone\" : \"phone\", \"children\" : [ { \"firstName\" : \"firstName\", \"lastName\" : \"lastName\", \"dob\" : \"dob\", \"sex\" : \"sex\", \"id\" : 1 }, { \"firstName\" : \"firstName\", \"lastName\" : \"lastName\", \"dob\" : \"dob\", \"sex\" : \"sex\", \"id\" : 1 } ], \"parentStatus\" : 6, \"id\" : 0, \"email\" : \"email\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /parent/byEmail/{email} : Get parent by email
     * This can be done by respective user or admin
     *
     * @param email Email of the parent to get (required)
     * @return Successful operation (status code 200)
     *         or Operation failed (status code 400)
     */
    @Operation(
            operationId = "getParentByEmail",
            summary = "Get parent by email",
            tags = { "Parent" },
            responses = {
                    @ApiResponse(responseCode = "200", description = "Successful operation", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = ParentDto.class))
                    }),
                    @ApiResponse(responseCode = "400", description = "Operation failed")
            }
    )
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/parent/byEmail/{email}",
            produces = { "application/json" }
    )
    default ResponseEntity<ParentDto> getParentByEmail(
            @Parameter(name = "email", description = "Email of the parent to get", required = true) @PathVariable("email") String email
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"firstName\" : \"firstName\", \"lastName\" : \"lastName\", \"password\" : \"password\", \"address\" : { \"country\" : \"country\", \"address\" : \"address\", \"city\" : \"city\", \"postalCode\" : \"postalCode\", \"state\" : \"state\", \"locationCoordinates\" : \"locationCoordinates\", \"apartment\" : \"apartment\" }, \"phone\" : \"phone\", \"children\" : [ { \"firstName\" : \"firstName\", \"lastName\" : \"lastName\", \"dob\" : \"dob\", \"sex\" : \"sex\", \"id\" : 1 }, { \"firstName\" : \"firstName\", \"lastName\" : \"lastName\", \"dob\" : \"dob\", \"sex\" : \"sex\", \"id\" : 1 } ], \"parentStatus\" : 6, \"id\" : 0, \"email\" : \"email\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /parent : Get Parent list
     * This can be done by admin only
     *
     * @return Successful operation (status code 200)
     *         or Operation failed (status code 400)
     */
    @Operation(
            operationId = "listParents",
            summary = "Get Parent list",
            tags = { "Parent" },
            responses = {
                    @ApiResponse(responseCode = "200", description = "Successful operation", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = ParentDto.class))
                    }),
                    @ApiResponse(responseCode = "400", description = "Operation failed")
            }
    )
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/parent",
            produces = { "application/json" }
    )
    default ResponseEntity<List<ParentDto>> listParents(

    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"firstName\" : \"firstName\", \"lastName\" : \"lastName\", \"password\" : \"password\", \"address\" : { \"country\" : \"country\", \"address\" : \"address\", \"city\" : \"city\", \"postalCode\" : \"postalCode\", \"state\" : \"state\", \"locationCoordinates\" : \"locationCoordinates\", \"apartment\" : \"apartment\" }, \"phone\" : \"phone\", \"children\" : [ { \"firstName\" : \"firstName\", \"lastName\" : \"lastName\", \"dob\" : \"dob\", \"sex\" : \"sex\", \"id\" : 1 }, { \"firstName\" : \"firstName\", \"lastName\" : \"lastName\", \"dob\" : \"dob\", \"sex\" : \"sex\", \"id\" : 1 } ], \"parentStatus\" : 6, \"id\" : 0, \"email\" : \"email\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
